DROP TABLE IF EXISTS WaterPipeline;
DROP TABLE IF EXISTS Point;
DROP TABLE IF EXISTS Result;

CREATE TABLE WaterPipeline (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idX INT,
  idY INT,
  length INT
);

CREATE TABLE Point (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idA INT,
  idB INT
);

CREATE TABLE Result (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ROUTE_EXISTS VARCHAR(250) NOT NULL,
  MIN_LENGTH VARCHAR(250)
);


